In [1]:
# deconvolute the TIME for TCGA dataset

library(tibble)
library(immunedeconv)

Loading required package: EPIC

In [2]:
load("../data/prad_data_tcga.RData")

In [3]:
# deconvolution
res.deconv <- deconvolute(as.matrix(prad.gene), "mcp_counter", tumor = TRUE)

>>> Running mcp_counter

In [8]:
res.deconv

   cell_type                    TCGA.2A.A8VL TCGA.2A.A8VO TCGA.2A.A8VT
1  T cell                         21.516857    31.284693    29.963229
2  T cell CD8+                    26.776500    21.267900   116.544100
3  cytotoxicity score             19.376186    14.811571    22.899143
4  NK cell                         2.639012     3.240038     2.297775
5  B cell                         44.863537    39.212700    16.590062
6  Monocyte                      249.448286   155.046786   322.716914
7  Macrophage/Monocyte           249.448286   155.046786   322.716914
8  Myeloid dendritic cell         15.756960    34.560320    16.470580
9  Neutrophil                    908.170267   678.224440  1224.485287
10 Endothelial cell              252.327497   270.050047   250.077457
11 Cancer associated fibroblast 6413.695938  8127.659725  3406.471975
   TCGA.2A.A8VV TCGA.2A.A8VX TCGA.2A.A8W1 TCGA.2A.A8W3 TCGA.2A.AAYF
1     14.926129   20.909443     6.813171    21.555621    19.100164
2     19.296400   29.726700     4.249800    22.490300    13.582300
3     11.564400    4.842629     7.555186    29.762529     8.185771
4      1.647238    2.015375     0.649275     2.606812     1.432513
5     75.773612 1046.605362    38.720337    18.401138    53.798800
6    312.977986  338.721314   142.941486   218.301843   125.151586
7    312.977986  338.721314   142.941486   218.301843   125.151586
8     21.649600   15.115260     8.027400    26.415860    21.392160
9   2050.186287  514.657593  1632.424353   929.380493  1030.984720
10   307.563870  120.030730    97.072847   460.685487   212.203317
11 10143.938700 7660.790412   977.293700  6531.122463  5331.602825
   TCGA.2A.AAYO ⋯ TCGA.ZG.A9LN TCGA.ZG.A9LS TCGA.ZG.A9LU TCGA.ZG.A9LY
1    108.472550 ⋯   211.725650   148.819179   64.448843     34.988507
2     64.499200 ⋯   220.451400    81.037300   41.441000     34.716300
3     33.260929 ⋯   153.753671    85.899500   50.724871     35.079243
4      9.242262 ⋯     8.483375     4.153162    4.709213      2.063938
5    335.736750 ⋯   715.940600   207.252825   20.014125     48.475862
6    310.435257 ⋯   512.380757   440.842786  254.162600    416.463057
7    310.435257 ⋯   512.380757   440.842786  254.162600    416.463057
8     68.379660 ⋯   177.858900   121.880040   54.438420     41.236240
9    487.537153 ⋯   568.368407   394.651553  535.217000    714.366367
10   378.481570 ⋯   319.238640   591.346303  310.560867    399.591727
11 11806.649187 ⋯ 17300.374425 21187.699550 8761.829537  11663.474813
   TCGA.ZG.A9LZ TCGA.ZG.A9M4 TCGA.ZG.A9MC TCGA.ZG.A9N3 TCGA.ZG.A9ND
1    43.53843    105.38842     222.25799    76.092843    14.1300857
2    51.78840    121.31570      98.09810    34.927900    13.8337000
3    41.47276    109.74859      82.79707    27.883586    34.8805571
4     3.21350      8.75695       5.25525     2.054575     0.6916875
5    50.48434     91.20034     400.77579   441.991512   899.6195750
6   605.16181    201.86733     476.47649   201.348829   106.9143571
7   605.16181    201.86733     476.47649   201.348829   106.9143571
8    38.45006    106.87740     116.11610    33.489660    14.3870200
9  1660.73026    603.78757     863.22989   560.626387  1752.5390600
10  230.90313    592.98162     512.83733   180.739343   263.2864200
11 4713.44262   3687.45889   10418.09370  8315.180263  4047.4909250
   TCGA.ZG.A9NI
1     29.844886
2     13.526800
3      8.481114
4      2.066600
5      8.923937
6    295.550214
7    295.550214
8     33.666740
9    459.160293
10   569.346480
11 24026.088912

In [11]:
# remove the row "cytotoxicity score" which is not a cell type
res.deconv <- res.deconv[res.deconv$cell_type != "cytotoxicity score", ]

In [12]:
res.deconv

   cell_type                    TCGA.2A.A8VL TCGA.2A.A8VO TCGA.2A.A8VT
1  T cell                         21.516857    31.284693    29.963229
2  T cell CD8+                    26.776500    21.267900   116.544100
3  NK cell                         2.639012     3.240038     2.297775
4  B cell                         44.863537    39.212700    16.590062
5  Monocyte                      249.448286   155.046786   322.716914
6  Macrophage/Monocyte           249.448286   155.046786   322.716914
7  Myeloid dendritic cell         15.756960    34.560320    16.470580
8  Neutrophil                    908.170267   678.224440  1224.485287
9  Endothelial cell              252.327497   270.050047   250.077457
10 Cancer associated fibroblast 6413.695938  8127.659725  3406.471975
   TCGA.2A.A8VV TCGA.2A.A8VX TCGA.2A.A8W1 TCGA.2A.A8W3 TCGA.2A.AAYF
1     14.926129   20.909443     6.813171    21.555621    19.100164
2     19.296400   29.726700     4.249800    22.490300    13.582300
3      1.647238    2.015375     0.649275     2.606812     1.432513
4     75.773612 1046.605362    38.720337    18.401138    53.798800
5    312.977986  338.721314   142.941486   218.301843   125.151586
6    312.977986  338.721314   142.941486   218.301843   125.151586
7     21.649600   15.115260     8.027400    26.415860    21.392160
8   2050.186287  514.657593  1632.424353   929.380493  1030.984720
9    307.563870  120.030730    97.072847   460.685487   212.203317
10 10143.938700 7660.790412   977.293700  6531.122463  5331.602825
   TCGA.2A.AAYO ⋯ TCGA.ZG.A9LN TCGA.ZG.A9LS TCGA.ZG.A9LU TCGA.ZG.A9LY
1    108.472550 ⋯   211.725650   148.819179   64.448843     34.988507
2     64.499200 ⋯   220.451400    81.037300   41.441000     34.716300
3      9.242262 ⋯     8.483375     4.153162    4.709213      2.063938
4    335.736750 ⋯   715.940600   207.252825   20.014125     48.475862
5    310.435257 ⋯   512.380757   440.842786  254.162600    416.463057
6    310.435257 ⋯   512.380757   440.842786  254.162600    416.463057
7     68.379660 ⋯   177.858900   121.880040   54.438420     41.236240
8    487.537153 ⋯   568.368407   394.651553  535.217000    714.366367
9    378.481570 ⋯   319.238640   591.346303  310.560867    399.591727
10 11806.649187 ⋯ 17300.374425 21187.699550 8761.829537  11663.474813
   TCGA.ZG.A9LZ TCGA.ZG.A9M4 TCGA.ZG.A9MC TCGA.ZG.A9N3 TCGA.ZG.A9ND
1    43.53843    105.38842     222.25799    76.092843    14.1300857
2    51.78840    121.31570      98.09810    34.927900    13.8337000
3     3.21350      8.75695       5.25525     2.054575     0.6916875
4    50.48434     91.20034     400.77579   441.991512   899.6195750
5   605.16181    201.86733     476.47649   201.348829   106.9143571
6   605.16181    201.86733     476.47649   201.348829   106.9143571
7    38.45006    106.87740     116.11610    33.489660    14.3870200
8  1660.73026    603.78757     863.22989   560.626387  1752.5390600
9   230.90313    592.98162     512.83733   180.739343   263.2864200
10 4713.44262   3687.45889   10418.09370  8315.180263  4047.4909250
   TCGA.ZG.A9NI
1     29.844886
2     13.526800
3      2.066600
4      8.923937
5    295.550214
6    295.550214
7     33.666740
8    459.160293
9    569.346480
10 24026.088912

In [13]:
res.deconv.mcpcounter <- column_to_rownames(res.deconv, colnames(res.deconv)[1])

res.deconv.sample <- as.data.frame(t(res.deconv.mcpcounter))

In [14]:
time.mcpcounter.bcr <- merge(res.deconv.sample, df.clinical.bcr[, c("bcr_days", "biochemical_recurrence")], by = "row.names")
time.mcpcounter.bcr <- column_to_rownames(time.mcpcounter.bcr, colnames(time.mcpcounter.bcr)[1])

In [15]:
write.csv(time.mcpcounter.bcr, "../data/time_mcpcounter_bcr_tcga.csv")
save(res.deconv.mcpcounter, prad.gene, df.clinical.bcr, time.mcpcounter.bcr, file = "../data/tcga_time_deconv_mcpcounter.RData")